---
title: "Sales Regression: Forecasting Demand"
author: "Mark Culp"
date: "August 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, fig.align = "center")

options(scipen = 999)

library(dplyr)
library(scales)
library(readxl)
library(ggplot2)
library(reshape2)
library(lubridate)


```



```{r}

# ==================== Regression Example ====================

# Read in Sales Regression data
sr <- read_xlsx("RFundX_2017_M1_2_Sales_Regression.xlsx", "All Data", "A2:C166")

# Create trend column
sr$Trend <- 1:164

# Create matrix columns for months
m <- matrix(0L,nrow = 164, ncol = 12)

# Convert to DF
m <- as.data.frame(m)

# Get vector of column numbers: 1 if true
one <- as.numeric(format(sr$Week,"%m"))

# Place 1 in col from matching month
for (i in 1:164) {
  m[i, one[i]] <- 1
}

# Combine month data
sr <- cbind(sr, m)

# Fit the Linear Model Using all Variables
fitAllModel <- lm(sr$Sales ~ sr$`Total Promos` + sr$Trend + 
            factor(sr$V1) + factor(sr$V2) + factor(sr$V3) + factor(sr$V4) +
            factor(sr$V5) + factor(sr$V6) + factor(sr$V7) + factor(sr$V8) +
            factor(sr$V9) + factor(sr$V10) + factor(sr$V11) + factor(sr$V12))

# Generate predicted values fm linear model
All_Model <- predict(fitAllModel)

# Get Week and Actual Demand/Sales data
srPlot <- sr[,1:2]

# Bind Forecast to Actual data
srPlot <- cbind(srPlot, All_Model)

# Melt data w reshape2 lib
srPlotLong <- melt(srPlot, id="Week")

# Create plot
g <-  ggplot(srPlotLong, aes(x = Week, y=value/1000, color=variable)) + 
  ggtitle("Sales vs. Model: All Data") +
  labs(x="Week", y="Sales  (000s)") +
  geom_line() +
  scale_y_continuous(label = dollar_format(),
      limits = c(min(srPlotLong$value),max(srPlotLong$value))/1000)

# Print plot
g


```


```{r}

# ================ Regression Forecast Example ===============

# Now use only historical data through Week 125
# to generate a forecast for the remaining weeks.

# Remove Week column from data as it is 
# not used as a regression variable
srVars <- sr[,2:16]

# Fit the model using only the first
# 125 weeks of data
fit125 <- lm(Sales ~ ., srVars[1:125,])

# Summarize Linear model (lm)
summary(fit125)

# Generate predicted values from
# the lm for the next 39 weeks
Forecast_All <- predict(fit125, srVars[126:164,])
rm(srVars)

# Get Week 126-164 and Actual Demand/Sales data
srPlot <- sr[126:164,1:2]

# Bind Forecast to Actual data
srPlot <- cbind(srPlot, Forecast_All)

# Melt data w reshape2 lib
srPlotLong <- melt(srPlot, id="Week")
rm(srPlot)

# Create plot
g = ggplot(srPlotLong, aes(x = Week, y=value/1000, color=variable))

g = g + ggtitle("Sales vs. Forecast: Week 125")

g = g + geom_line()

g = g + scale_y_continuous(label = dollar_format(),
                           limits = c(min(srPlotLong$value),max(srPlotLong$value))/1000)

g = g + labs(x="Week", y="Sales  (000s)")

g
rm(g, srPlotLong)


```